// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlc1QK3nHMxcOW_AwgEjrByCoklSxoiTY',
    appId: '1:632145227488:web:5a232c27b89eda7d17ea85',
    messagingSenderId: '632145227488',
    projectId: 'myapp-e3d24',
    authDomain: 'myapp-e3d24.firebaseapp.com',
    storageBucket: 'myapp-e3d24.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfKnQO2Rmiy6PkX3A3YNAR0xs-GzYcIjo',
    appId: '1:632145227488:android:2f2b3ab09b2c2a1817ea85',
    messagingSenderId: '632145227488',
    projectId: 'myapp-e3d24',
    storageBucket: 'myapp-e3d24.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFRU8hDmhmZTUCq9S3vioxeaog58kJdcs',
    appId: '1:632145227488:ios:edc76a0da08113f717ea85',
    messagingSenderId: '632145227488',
    projectId: 'myapp-e3d24',
    storageBucket: 'myapp-e3d24.appspot.com',
    androidClientId: '632145227488-0mt91lec2n8dlr1k0cjm8nucdpt7aaki.apps.googleusercontent.com',
    iosClientId: '632145227488-lcaio74nro15vnrajlv0bot6h2htomij.apps.googleusercontent.com',
    iosBundleId: 'com.divinetechs.learningapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBFRU8hDmhmZTUCq9S3vioxeaog58kJdcs',
    appId: '1:632145227488:ios:edc76a0da08113f717ea85',
    messagingSenderId: '632145227488',
    projectId: 'myapp-e3d24',
    storageBucket: 'myapp-e3d24.appspot.com',
    androidClientId: '632145227488-0mt91lec2n8dlr1k0cjm8nucdpt7aaki.apps.googleusercontent.com',
    iosClientId: '632145227488-lcaio74nro15vnrajlv0bot6h2htomij.apps.googleusercontent.com',
    iosBundleId: 'com.divinetechs.learningapp',
  );
}
